title: Jeff Langlias # your name (or website title) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <span class="subhead">Designer. Developer.</span>
  <br><br>
  I excel under deadlines, keeping multiple projects for several clients on task and on schedule, and take pride in making every client feel like they’re the only one. I am a firm believer in, not only the ability to wear many hats, but the willingness to wear the ones that take you out of your comfort zone.
  <br><br>
  <a href="https://www.linkedin.com/in/jeffrey-t-langlais/">View My LinkedIn Profile</a>

theme: jekyll-theme-minimal
